// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_types.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countChildItemTypes = `-- name: CountChildItemTypes :one
SELECT COUNT(*) AS count
FROM item_types
WHERE parent_id = ?
`

func (q *Queries) CountChildItemTypes(ctx context.Context, parentID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChildItemTypes, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItemType = `-- name: CreateItemType :one
INSERT INTO item_types (parent_id, name, description, depth)
VALUES (?, ?, ?, ?)
RETURNING id, parent_id, name, description, depth, created_at
`

type CreateItemTypeParams struct {
	ParentID    sql.NullInt64  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Depth       int64          `json:"depth"`
}

func (q *Queries) CreateItemType(ctx context.Context, arg CreateItemTypeParams) (ItemType, error) {
	row := q.db.QueryRowContext(ctx, createItemType,
		arg.ParentID,
		arg.Name,
		arg.Description,
		arg.Depth,
	)
	var i ItemType
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.Depth,
		&i.CreatedAt,
	)
	return i, err
}

const createRootItemType = `-- name: CreateRootItemType :one
INSERT INTO item_types (parent_id, name, description, depth)
VALUES (NULL, ?, ?, 0)
RETURNING id, parent_id, name, description, depth, created_at
`

type CreateRootItemTypeParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateRootItemType(ctx context.Context, arg CreateRootItemTypeParams) (ItemType, error) {
	row := q.db.QueryRowContext(ctx, createRootItemType, arg.Name, arg.Description)
	var i ItemType
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.Depth,
		&i.CreatedAt,
	)
	return i, err
}

const deleteItemType = `-- name: DeleteItemType :exec
DELETE FROM item_types WHERE id = ?
`

func (q *Queries) DeleteItemType(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteItemType, id)
	return err
}

const getItemType = `-- name: GetItemType :one
SELECT id, parent_id, name, description, depth, created_at
FROM item_types
WHERE id = ?
`

func (q *Queries) GetItemType(ctx context.Context, id int64) (ItemType, error) {
	row := q.db.QueryRowContext(ctx, getItemType, id)
	var i ItemType
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.Depth,
		&i.CreatedAt,
	)
	return i, err
}

const getItemTypeAncestors = `-- name: GetItemTypeAncestors :many
WITH RECURSIVE ancestors AS (
    SELECT id, parent_id, name, description, depth, created_at
    FROM item_types
    WHERE item_types.id = ?1
    UNION ALL
    SELECT it.id, it.parent_id, it.name, it.description, it.depth, it.created_at
    FROM item_types it, ancestors a
    WHERE it.id = a.parent_id
)
SELECT id, parent_id, name, description, depth, created_at FROM ancestors
ORDER BY depth
`

type GetItemTypeAncestorsRow struct {
	ID          int64          `json:"id"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Depth       int64          `json:"depth"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetItemTypeAncestors(ctx context.Context, typeID int64) ([]GetItemTypeAncestorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemTypeAncestors, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetItemTypeAncestorsRow{}
	for rows.Next() {
		var i GetItemTypeAncestorsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Depth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemTypeDescendants = `-- name: GetItemTypeDescendants :many
WITH RECURSIVE descendants AS (
    SELECT id, parent_id, name, description, depth, created_at
    FROM item_types
    WHERE item_types.id = ?1
    UNION ALL
    SELECT it.id, it.parent_id, it.name, it.description, it.depth, it.created_at
    FROM item_types it, descendants d
    WHERE it.parent_id = d.id
)
SELECT id, parent_id, name, description, depth, created_at FROM descendants
ORDER BY depth, name
`

type GetItemTypeDescendantsRow struct {
	ID          int64          `json:"id"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Depth       int64          `json:"depth"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetItemTypeDescendants(ctx context.Context, typeID int64) ([]GetItemTypeDescendantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemTypeDescendants, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetItemTypeDescendantsRow{}
	for rows.Next() {
		var i GetItemTypeDescendantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Depth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemTypePath = `-- name: GetItemTypePath :many
WITH RECURSIVE path AS (
    SELECT id, parent_id, name, description, depth, created_at
    FROM item_types
    WHERE item_types.id = ?1
    UNION ALL
    SELECT it.id, it.parent_id, it.name, it.description, it.depth, it.created_at
    FROM item_types it, path p
    WHERE it.id = p.parent_id
)
SELECT id, parent_id, name, description, depth, created_at FROM path
ORDER BY depth ASC
`

type GetItemTypePathRow struct {
	ID          int64          `json:"id"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Depth       int64          `json:"depth"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetItemTypePath(ctx context.Context, typeID int64) ([]GetItemTypePathRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemTypePath, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetItemTypePathRow{}
	for rows.Next() {
		var i GetItemTypePathRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Depth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isLeafItemType = `-- name: IsLeafItemType :one
SELECT CASE
    WHEN COUNT(*) = 0 THEN 1
    ELSE 0
END AS is_leaf
FROM item_types
WHERE parent_id = ?
`

func (q *Queries) IsLeafItemType(ctx context.Context, parentID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, isLeafItemType, parentID)
	var is_leaf int64
	err := row.Scan(&is_leaf)
	return is_leaf, err
}

const listChildItemTypes = `-- name: ListChildItemTypes :many
SELECT id, parent_id, name, description, depth, created_at
FROM item_types
WHERE parent_id = ?
ORDER BY name
`

func (q *Queries) ListChildItemTypes(ctx context.Context, parentID sql.NullInt64) ([]ItemType, error) {
	rows, err := q.db.QueryContext(ctx, listChildItemTypes, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemType{}
	for rows.Next() {
		var i ItemType
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Depth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTypes = `-- name: ListItemTypes :many
SELECT id, parent_id, name, description, depth, created_at
FROM item_types
ORDER BY depth, name
`

func (q *Queries) ListItemTypes(ctx context.Context) ([]ItemType, error) {
	rows, err := q.db.QueryContext(ctx, listItemTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemType{}
	for rows.Next() {
		var i ItemType
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Depth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeafItemTypes = `-- name: ListLeafItemTypes :many
SELECT it.id, it.parent_id, it.name, it.description, it.depth, it.created_at
FROM item_types it
WHERE NOT EXISTS (
    SELECT 1 FROM item_types AS children WHERE children.parent_id = it.id
)
ORDER BY it.name
`

func (q *Queries) ListLeafItemTypes(ctx context.Context) ([]ItemType, error) {
	rows, err := q.db.QueryContext(ctx, listLeafItemTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemType{}
	for rows.Next() {
		var i ItemType
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Depth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootItemTypes = `-- name: ListRootItemTypes :many
SELECT id, parent_id, name, description, depth, created_at
FROM item_types
WHERE parent_id IS NULL
ORDER BY name
`

func (q *Queries) ListRootItemTypes(ctx context.Context) ([]ItemType, error) {
	rows, err := q.db.QueryContext(ctx, listRootItemTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemType{}
	for rows.Next() {
		var i ItemType
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Depth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
