// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countItemsByType = `-- name: CountItemsByType :one
SELECT COUNT(*) AS count
FROM items
WHERE item_type_id = ?
`

func (q *Queries) CountItemsByType(ctx context.Context, itemTypeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItemsByType, itemTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (name, item_type_id, quantity, unit_type)
VALUES (?, ?, ?, ?)
RETURNING id, name, item_type_id, quantity, unit_type, created_at
`

type CreateItemParams struct {
	Name       string  `json:"name"`
	ItemTypeID int64   `json:"item_type_id"`
	Quantity   float64 `json:"quantity"`
	UnitType   string  `json:"unit_type"`
}

type CreateItemRow struct {
	ID         int64   `json:"id"`
	Name       string  `json:"name"`
	ItemTypeID int64   `json:"item_type_id"`
	Quantity   float64 `json:"quantity"`
	UnitType   string  `json:"unit_type"`
	CreatedAt  string  `json:"created_at"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.Name,
		arg.ItemTypeID,
		arg.Quantity,
		arg.UnitType,
	)
	var i CreateItemRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ItemTypeID,
		&i.Quantity,
		&i.UnitType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items WHERE id = ?
`

func (q *Queries) DeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteItem, id)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, name, item_type_id, quantity, unit_type, created_at
FROM items
WHERE id = ?
`

type GetItemRow struct {
	ID         int64   `json:"id"`
	Name       string  `json:"name"`
	ItemTypeID int64   `json:"item_type_id"`
	Quantity   float64 `json:"quantity"`
	UnitType   string  `json:"unit_type"`
	CreatedAt  string  `json:"created_at"`
}

func (q *Queries) GetItem(ctx context.Context, id int64) (GetItemRow, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i GetItemRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ItemTypeID,
		&i.Quantity,
		&i.UnitType,
		&i.CreatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, name, item_type_id, quantity, unit_type, created_at
FROM items
ORDER BY name
`

type ListItemsRow struct {
	ID         int64   `json:"id"`
	Name       string  `json:"name"`
	ItemTypeID int64   `json:"item_type_id"`
	Quantity   float64 `json:"quantity"`
	UnitType   string  `json:"unit_type"`
	CreatedAt  string  `json:"created_at"`
}

func (q *Queries) ListItems(ctx context.Context) ([]ListItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsRow{}
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ItemTypeID,
			&i.Quantity,
			&i.UnitType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByType = `-- name: ListItemsByType :many
SELECT id, name, item_type_id, quantity, unit_type, created_at
FROM items
WHERE item_type_id = ?
ORDER BY name
`

type ListItemsByTypeRow struct {
	ID         int64   `json:"id"`
	Name       string  `json:"name"`
	ItemTypeID int64   `json:"item_type_id"`
	Quantity   float64 `json:"quantity"`
	UnitType   string  `json:"unit_type"`
	CreatedAt  string  `json:"created_at"`
}

func (q *Queries) ListItemsByType(ctx context.Context, itemTypeID int64) ([]ListItemsByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByType, itemTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsByTypeRow{}
	for rows.Next() {
		var i ListItemsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ItemTypeID,
			&i.Quantity,
			&i.UnitType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsWithType = `-- name: ListItemsWithType :many
SELECT
    i.id,
    i.name,
    i.item_type_id,
    i.quantity,
    i.unit_type,
    i.created_at,
    t.name as type_name,
    t.parent_id as type_parent_id,
    t.depth as type_depth
FROM items i
JOIN item_types t ON i.item_type_id = t.id
ORDER BY i.name
`

type ListItemsWithTypeRow struct {
	ID           int64         `json:"id"`
	Name         string        `json:"name"`
	ItemTypeID   int64         `json:"item_type_id"`
	Quantity     float64       `json:"quantity"`
	UnitType     string        `json:"unit_type"`
	CreatedAt    string        `json:"created_at"`
	TypeName     string        `json:"type_name"`
	TypeParentID sql.NullInt64 `json:"type_parent_id"`
	TypeDepth    int64         `json:"type_depth"`
}

func (q *Queries) ListItemsWithType(ctx context.Context) ([]ListItemsWithTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemsWithType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsWithTypeRow{}
	for rows.Next() {
		var i ListItemsWithTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ItemTypeID,
			&i.Quantity,
			&i.UnitType,
			&i.CreatedAt,
			&i.TypeName,
			&i.TypeParentID,
			&i.TypeDepth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsWithTypePath = `-- name: ListItemsWithTypePath :many
SELECT
    i.id,
    i.name,
    i.item_type_id,
    i.quantity,
    i.unit_type,
    i.created_at,
    t.name as type_name,
    t.parent_id as type_parent_id,
    t.depth as type_depth
FROM items i
JOIN item_types t ON i.item_type_id = t.id
ORDER BY t.depth, t.name, i.name
`

type ListItemsWithTypePathRow struct {
	ID           int64         `json:"id"`
	Name         string        `json:"name"`
	ItemTypeID   int64         `json:"item_type_id"`
	Quantity     float64       `json:"quantity"`
	UnitType     string        `json:"unit_type"`
	CreatedAt    string        `json:"created_at"`
	TypeName     string        `json:"type_name"`
	TypeParentID sql.NullInt64 `json:"type_parent_id"`
	TypeDepth    int64         `json:"type_depth"`
}

func (q *Queries) ListItemsWithTypePath(ctx context.Context) ([]ListItemsWithTypePathRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemsWithTypePath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsWithTypePathRow{}
	for rows.Next() {
		var i ListItemsWithTypePathRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ItemTypeID,
			&i.Quantity,
			&i.UnitType,
			&i.CreatedAt,
			&i.TypeName,
			&i.TypeParentID,
			&i.TypeDepth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :exec
UPDATE items
SET name = ?, item_type_id = ?, quantity = ?, unit_type = ?
WHERE id = ?
`

type UpdateItemParams struct {
	Name       string  `json:"name"`
	ItemTypeID int64   `json:"item_type_id"`
	Quantity   float64 `json:"quantity"`
	UnitType   string  `json:"unit_type"`
	ID         int64   `json:"id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.ExecContext(ctx, updateItem,
		arg.Name,
		arg.ItemTypeID,
		arg.Quantity,
		arg.UnitType,
		arg.ID,
	)
	return err
}
