// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countChildLocations = `-- name: CountChildLocations :one
SELECT COUNT(*) AS count
FROM locations
WHERE parent_id = ?
`

func (q *Queries) CountChildLocations(ctx context.Context, parentID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChildLocations, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItemsByLocation = `-- name: CountItemsByLocation :one
SELECT COUNT(*) AS count
FROM items
WHERE location_id = ?
`

func (q *Queries) CountItemsByLocation(ctx context.Context, locationID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItemsByLocation, locationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (parent_id, name, description, depth)
VALUES (?, ?, ?, ?)
RETURNING id, parent_id, name, description, depth, created_at
`

type CreateLocationParams struct {
	ParentID    sql.NullInt64  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Depth       int64          `json:"depth"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation,
		arg.ParentID,
		arg.Name,
		arg.Description,
		arg.Depth,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.Depth,
		&i.CreatedAt,
	)
	return i, err
}

const createRootLocation = `-- name: CreateRootLocation :one
INSERT INTO locations (parent_id, name, description, depth)
VALUES (NULL, ?, ?, 0)
RETURNING id, parent_id, name, description, depth, created_at
`

type CreateRootLocationParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateRootLocation(ctx context.Context, arg CreateRootLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, createRootLocation, arg.Name, arg.Description)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.Depth,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = ?
`

func (q *Queries) DeleteLocation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLocation, id)
	return err
}

const getLocation = `-- name: GetLocation :one
SELECT id, parent_id, name, description, depth, created_at
FROM locations
WHERE id = ?
`

func (q *Queries) GetLocation(ctx context.Context, id int64) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.Depth,
		&i.CreatedAt,
	)
	return i, err
}

const getLocationAncestors = `-- name: GetLocationAncestors :many
WITH RECURSIVE ancestors AS (
    SELECT id, parent_id, name, description, depth, created_at
    FROM locations
    WHERE locations.id = ?1
    UNION ALL
    SELECT l.id, l.parent_id, l.name, l.description, l.depth, l.created_at
    FROM locations l, ancestors a
    WHERE l.id = a.parent_id
)
SELECT id, parent_id, name, description, depth, created_at FROM ancestors
ORDER BY depth
`

type GetLocationAncestorsRow struct {
	ID          int64          `json:"id"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Depth       int64          `json:"depth"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetLocationAncestors(ctx context.Context, locationID int64) ([]GetLocationAncestorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLocationAncestors, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLocationAncestorsRow{}
	for rows.Next() {
		var i GetLocationAncestorsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Depth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationDescendants = `-- name: GetLocationDescendants :many
WITH RECURSIVE descendants AS (
    SELECT id, parent_id, name, description, depth, created_at
    FROM locations
    WHERE locations.id = ?1
    UNION ALL
    SELECT l.id, l.parent_id, l.name, l.description, l.depth, l.created_at
    FROM locations l, descendants d
    WHERE l.parent_id = d.id
)
SELECT id, parent_id, name, description, depth, created_at FROM descendants
ORDER BY depth, name
`

type GetLocationDescendantsRow struct {
	ID          int64          `json:"id"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Depth       int64          `json:"depth"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetLocationDescendants(ctx context.Context, locationID int64) ([]GetLocationDescendantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLocationDescendants, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLocationDescendantsRow{}
	for rows.Next() {
		var i GetLocationDescendantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Depth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationPath = `-- name: GetLocationPath :many
WITH RECURSIVE path AS (
    SELECT id, parent_id, name, description, depth, created_at
    FROM locations
    WHERE locations.id = ?1
    UNION ALL
    SELECT l.id, l.parent_id, l.name, l.description, l.depth, l.created_at
    FROM locations l, path p
    WHERE l.id = p.parent_id
)
SELECT id, parent_id, name, description, depth, created_at FROM path
ORDER BY depth ASC
`

type GetLocationPathRow struct {
	ID          int64          `json:"id"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Depth       int64          `json:"depth"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetLocationPath(ctx context.Context, locationID int64) ([]GetLocationPathRow, error) {
	rows, err := q.db.QueryContext(ctx, getLocationPath, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLocationPathRow{}
	for rows.Next() {
		var i GetLocationPathRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Depth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isLeafLocation = `-- name: IsLeafLocation :one
SELECT CASE
    WHEN COUNT(*) > 0 THEN 1
    ELSE 0
END AS is_leaf
FROM items
WHERE location_id = ?
`

func (q *Queries) IsLeafLocation(ctx context.Context, locationID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, isLeafLocation, locationID)
	var is_leaf int64
	err := row.Scan(&is_leaf)
	return is_leaf, err
}

const listChildLocations = `-- name: ListChildLocations :many
SELECT id, parent_id, name, description, depth, created_at
FROM locations
WHERE parent_id = ?
ORDER BY name
`

func (q *Queries) ListChildLocations(ctx context.Context, parentID sql.NullInt64) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listChildLocations, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Depth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByLocation = `-- name: ListItemsByLocation :many
SELECT id, name, item_type_id, location_id, quantity, unit_type, created_at
FROM items
WHERE location_id = ?
ORDER BY name
`

type ListItemsByLocationRow struct {
	ID         int64         `json:"id"`
	Name       string        `json:"name"`
	ItemTypeID int64         `json:"item_type_id"`
	LocationID sql.NullInt64 `json:"location_id"`
	Quantity   float64       `json:"quantity"`
	UnitType   string        `json:"unit_type"`
	CreatedAt  string        `json:"created_at"`
}

func (q *Queries) ListItemsByLocation(ctx context.Context, locationID sql.NullInt64) ([]ListItemsByLocationRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsByLocationRow{}
	for rows.Next() {
		var i ListItemsByLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ItemTypeID,
			&i.LocationID,
			&i.Quantity,
			&i.UnitType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeafLocations = `-- name: ListLeafLocations :many
SELECT l.id, l.parent_id, l.name, l.description, l.depth, l.created_at
FROM locations l
WHERE NOT EXISTS (
    SELECT 1 FROM locations AS children WHERE children.parent_id = l.id
)
ORDER BY l.name
`

func (q *Queries) ListLeafLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listLeafLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Depth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, parent_id, name, description, depth, created_at
FROM locations
ORDER BY depth, name
`

func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Depth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootLocations = `-- name: ListRootLocations :many
SELECT id, parent_id, name, description, depth, created_at
FROM locations
WHERE parent_id IS NULL
ORDER BY name
`

func (q *Queries) ListRootLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listRootLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Depth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
