// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Item struct {
	ID         int64         `json:"id"`
	Name       string        `json:"name"`
	ItemTypeID int64         `json:"item_type_id"`
	CreatedAt  string        `json:"created_at"`
	Quantity   float64       `json:"quantity"`
	UnitType   string        `json:"unit_type"`
	LocationID sql.NullInt64 `json:"location_id"`
}

type ItemType struct {
	ID          int64          `json:"id"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Depth       int64          `json:"depth"`
	CreatedAt   string         `json:"created_at"`
}

type Location struct {
	ID          int64          `json:"id"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Depth       int64          `json:"depth"`
	CreatedAt   string         `json:"created_at"`
}
